### ISSUE TITLE
Multiple errors on WBCE 1.2-alpha 4

### ISSUE THREAD

**Issue by instantflorian** [WBCE/news#1]
Installation fails due to line 19 in install.php:
`require_once( dirname(dirname(dirname(__FILE__))).'/framework/globalExceptionHandler.php');`
File doesn't exist

Unable to create groups or news items
Fatal error: Cannot redeclare rm_full_dir() (previously declared in /.../framework/functions.php:27) in /.../framework/functions.php on line 64

**Comment by NorHei** [comment]
Ok the first one , what install.php you are talking about ?? The main installer is in an index.php ?

I guess this is module news , so i guess you have a test installation for me to take a look ?

**Comment by NorHei** [comment]
ahhh dam we are in the news module herre .. i just clicked the mail link ..

**Comment by NorHei** [comment]
wbce0511 habe ich das news modul installiert , keine probleme mehr .. 

schau bitte mal drüber

**Comment by instantflorian** [comment]
Installation + News anlegen geht. Kein Output im Frontend:
Fatal error: Call to a member function page_link() on a non-object in .../framework/functions.php on line 596

**Comment by NorHei** [comment]
Should have been fixed by now ,,, you have mail ...

**Comment by NorHei** [comment]
Added One more compatibility fix to address the very first issue.

**Comment by NorHei** [comment]
Ups the last one was a fix on the core ... but anyway it should be ok by now

**Comment by instantflorian** [comment]
can confirm, now everything works fine :)
